name: chatdb
description: A AI application inspired from ChatGPT that communicates with databases
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  shared_preferences:  ^2.2.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^1.1.0
  flutter_glow: ^0.3.0
  animations: ^2.0.7
  font_awesome_flutter: ^10.5.0
  line_icons: ^2.0.3
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  google_sign_in: ^6.1.4
  sqflite: ^2.3.0
  path: ^1.8.3
  excel: ^4.0.6
  file_picker: ^8.1.7
  excel_to_json: ^1.1.0
  cloud_firestore: ^5.6.1
  firebase_dynamic_links: ^6.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/icon1.svg
    - images/icon2.jpg
    - images/icon3.svg
    - images/icon4.svg
  fonts:
    - family: Gabriola
      fonts:
        - asset: fonts/Gabriola.ttf
    - family: LucidaSans
      fonts:
        - asset: fonts/LucidaSans.ttf
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Medium.ttf
    - family: DaysOne
      fonts:
        - asset: fonts/DaysOne-Regular.ttf


